USE dosijeprof;

CREATE TABLE IF NOT EXISTS korisnik
(
    id INTEGER NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    ime VARCHAR(50) NULL DEFAULT NULL,
    prezime VARCHAR(50) NULL DEFAULT NULL,

    PRIMARY KEY(id)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS podaci
(
    id INTEGER NOT NULL AUTO_INCREMENT,
    ime VARCHAR(50) NULL DEFAULT NULL,
    prezime VARCHAR(50) NULL DEFAULT NULL,
    pol VARCHAR(1) NULL DEFAULT NULL,
    jmbg VARCHAR(13) NULL DEFAULT NULL,
    datum_rodjenja DATETIME NULL DEFAULT NULL,
    adresa VARCHAR(100) NULL DEFAULT NULL,
    nacionalnost VARCHAR(50) NULL DEFAULT NULL,
    bracno_stanje VARCHAR(50) NULL DEFAULT NULL,
    slika VARCHAR(100) NULL DEFAULT NULL,
    ostali_podaci TEXT NULL DEFAULT NULL,
    misljenje TEXT NULL DEFAULT NULL,

    PRIMARY KEY(id)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=InnoDB;
